### ISSUE TITLE
频繁出现检测到验证码

### ISSUE THREAD

**Issue by mulinAi** [Jici-Zeroten/XiaoFeiShu#1]
频繁出现检测到验证码，需要人工去校验的情况，会不会被小红书识别到是矩阵养号呢

**Comment by Jici-Zeroten** [comment]
截至此回复时间 （2024.12.11晚19:00）的最新测试，并不存在你所说的【频繁出现检测到验证码 】的情况，且没有其他用户反映类似问题。请检查你是否按照我们产品的用户协议和手册正确使用软件，以及检查除软件之外的其他导致风控的因素，如敏感设备、风控账号/手机号、风险网络环境、不干净的代理等因素，如果你仍存在此类情况，请录制相应视频联系并提交给我们相关的工作人员。

**Comment by mulinAi** [comment]
我是看你们b站宣传视频里面的，有高频出现的这个验证码跳出提示，所以问这个问题
![94d9dabf5afb214800f618c4e446240](https://github.com/user-attachments/assets/668d9f24-0104-4325-84b7-e7c0ed6d4e24)
